openapi: 3.0.0
info:
  title: Express FischkappAPI with Swagger
  version: 0.1.0
  description: This is a simple CRUD API application made with Express and documented with Swagger
  contact:
    name: Ajmag
    url: https://github.com/Wiecek-K/
    email: krystiandwiecek@gmail.com
servers:
  - url: http://localhost:4000/docs
